export const APP_ROUTE_SEGMENTS = {
  AUTH: 'auth',
  LOGIN: 'login',
  FORGOT_PASSWORD: 'forgot-password',
  RESET_PASSWORD: 'reset-password',
  DASHBOARD: '',
  PROFILE: 'profile',
  ACCOUNT: 'account',
  PASSWORD: 'password',
  DOCUMENTS: 'documents',
  BILLING: 'billing',
  FAQ: 'faq',
  CONTACT_US: 'contact-us',
};

export const APP_ROUTES = {
  LOGIN: `/${APP_ROUTE_SEGMENTS.AUTH}/${APP_ROUTE_SEGMENTS.LOGIN}`,
  FORGOT_PASSWORD: `/${APP_ROUTE_SEGMENTS.AUTH}/${APP_ROUTE_SEGMENTS.FORGOT_PASSWORD}`,
  RESET_PASSWORD: `/${APP_ROUTE_SEGMENTS.AUTH}/${APP_ROUTE_SEGMENTS.RESET_PASSWORD}`,
  DASHBOARD: `/${APP_ROUTE_SEGMENTS.DASHBOARD}`,
  PROFILE: `/${APP_ROUTE_SEGMENTS.PROFILE}`,
  ACCOUNT: `/${APP_ROUTE_SEGMENTS.PROFILE}/${APP_ROUTE_SEGMENTS.ACCOUNT}`,
  PASSWORD: `/${APP_ROUTE_SEGMENTS.PROFILE}/${APP_ROUTE_SEGMENTS.PASSWORD}`,
  DOCUMENTS: `/${APP_ROUTE_SEGMENTS.PROFILE}/${APP_ROUTE_SEGMENTS.DOCUMENTS}`,
  BILLING: `/${APP_ROUTE_SEGMENTS.BILLING}`,
  FAQ: `/${APP_ROUTE_SEGMENTS.FAQ}`,
  CONTACT_US: `/${APP_ROUTE_SEGMENTS.CONTACT_US}`,
};
